### ISSUE TITLE
Wondering about how GMM is calculated

### ISSUE THREAD

**Issue by EverettBerry** [suriyasingh/EgoConvNet#1]
Hello,

In the file `compute_fisher.m` you load several files which are the result of GMM computation, `gtea_gmm_full_sconv4.mat` for example. I see that those files are saved in the `ego_tdd/gmm` folder but their names don't match the code in `gmm.m`. There you save files with names like `gtea_gmm_segment_sconv4.mat`. So my first question is, did you use the same GMM procedure on the 'segment' files as the 'full' files?

Assuming that is the case, it would appear that you use the `do_decorrelate` function twice, once before GMM calculation and once after, in `compute_fisher.m` before the fisher vector is computed. I see that there are two different versions of this function, one does PCA and whitening and the other only does whitening. My second question is then why do you do whitening twice?

I appreciate your answers, I think your work is a very interesting extension to the original TDD paper.

Thank you for your time,
Everett

**Comment by kirbyk** [comment]
+1 would really love to hear about this

**Comment by salahsh** [comment]
Hello , 
In 'script_demo.m' you used  'vertcat' to concatenate the date  vertically from different scales and norms ,whereas  in 'gmm.m' you used 'horzcat' to concatenate the date  horizontally .  After that you used feature_sconv4 = full_feature(:, index_sconv4); 
This make confused ,because the data has different formats in 'script_demo.m' and 'gmm.m' .
